name: Push container to registry
on: 
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    name: Build container and push to Docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup docker
        uses: docker/setup-buildx-action@v1
      -
        name: Setup go
        uses: actions/setup-go@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push container to Docker
        run: make push
        env:
          GOOS: linux
          DOCKER_IMAGE_NAME: werkspot/configmap-reload
          DOCKER_IMAGE_TAG: ${{ github.ref }}
