name: Push container to registry
on: 
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build container and push to Docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup docker
        uses: docker/setup-buildx-action@v1
      -
        name: Setup go
        uses: actions/setup-go@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
      -
        name: Build container and push to Docker
        run: make push
        env:
          GOOS: linux
          DOCKER_IMAGE_NAME: werkspot/configmap-reload
          DOCKER_IMAGE_TAG: ${{ steps.extract_tag.outputs.tag }}
